### ISSUE TITLE
Shortcuts in Linux

### ISSUE THREAD

**Issue by liko28s** [piyushagade/UniClip-Linux#1]
Hi guys, note that the keyboard shortcuts in the linux application collide with those used in the operating system on most terminals and consoles, specifically ctrl+shift+v and ctrl+shift+c
can be changed for another combination?

**Comment by piyushagade** [comment]
Yes, you can definitely do that by changing the source code. You would need to install "asar" using npm.
The source code is an asar package (app.asar) and is located in the "resources" directory of the UniClip folder.
To install asar utility, use -> npm i -g asar
To unpack app.asar, use -> asar e app.asar app

In the new app folder, open'main.js', and search for "Shortkeys and Clipboard management".
Change:
var ret_accept = globalShortcut.register('ctrl+shift+c', function() { 
....

To:
var ret_accept = globalShortcut.register('{{ ANYTHING YOU WANT  }}', function() {
....

Save the 'main.js'. Now, delete the app.asar file. You can either let the app folder be in unpacked state, or you can pack it by using the following command "asar pack app app.asar" and then delete the app folder.

![image](https://user-images.githubusercontent.com/5830384/31129670-44dcb056-a823-11e7-8c43-dc11c827e8f2.png)
